name: mkdocs-main

on: pull_request

jobs:
  publish-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set dev version
        working-directory: ./java
        run: echo "DEV_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING')" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install deps
        working-directory: ./python
        run: cp ../README.md . && pip3 install -r ../requirements-docs.txt && pip3 install -e .[dev]

      - name: generate autodoc
        run: python3 auto_doc.py

      - name: setup git
        run: |
          git config --global user.name Mike
          git config --global user.email mike@docs.hopsworks.ai

      - name: mike deploy docs
        run: mike deploy ${{ env.DEV_VERSION }} dev -u
